name: (comfy-sonic-runpod-worker) Build and Push Docker Image

on:
    push:
        branches:
            - main

env:
    IMAGE_NAME: comfy-sonic-runpod-worker
    REGISTRY: ghcr.io
    USERNAME: ${{ github.repository_owner }}
    TAG: ${{ github.sha }}

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Delete huge unnecessary tools folder
              run: rm -rf /opt/hostedtoolcache

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ env.USERNAME }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: SonicDockerFile
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
